info:
  description: SMART COSMOS Cluster Services
  url: https://www.smart-cosmos.com/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  port: 0

server:
  port: 0

spring:
  redis:
    host: ${EVENT_SERVER_URL:localhost}
    password:
