server:
  port: 8080

management:
  port: 8081
  security:
    enabled: false

security:
  user:
    password: password

spring:
  datasource:
    #
    # CREATE DATABASE devkit;  GRANT ALL PRIVILEGES ON devkit.* TO 'cosmos'@'localhost' IDENTIFIED BY 'dev';  FLUSH PRIVILEGES;
    #
    url: jdbc:mysql://${smartcosmos.datasource.default-host}/${smartcosmos.datasource.default-db}
    username: ${smartcosmos.datasource.default-username}
    password: ${smartcosmos.datasource.default-password}
    driver-class-name: org.mariadb.jdbc.Driver
    ## XXX Note that in the migration to Spring Boot 1.4 these will need to move:
    test-on-borrow: true
    validation-query: SELECT 1
    ## Uncomment for Spring Boot 1.4
    # tomcat:
    #   test-on-borrow: true
    #   validation-query: SELECT 1
# XXX Super dangerous to let this get to production.
  jpa:
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy

smartcosmos:
  security:
    enabled: true

logging:
  level:
    ROOT: INFO
    net.smartcosmos: INFO
    org.springframework.security: INFO
    com.netflix.eureka.registry: INFO
