server:
  port: 45336

security:
  user:
    password: password

spring:
  datasource:
    url: jdbc:mysql://localhost/devkit?autoReconnect=true
    username: cosmos
    password: dev
    driver-class-name: com.mysql.jdbc.Driver

# XXX Super dangerous to let this get to production.
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    ROOT: INFO
    org.springframework:
      boot.autoconfigure.security.oauth2: TRACE
      security.oauth2: DEBUG
